name: close-matching-issues
description: Closes issues matching a query
branding:
  icon: check-circle
  color: red
inputs:
  token:
    description: Token to use to execute the search
    required: true
  query:
    description: Query to use to search for matching issues
    required: true
runs:
  using: 'node16'
  main: dist/index.js
