name: Test

on:
  pull_request:
  push:
    branches:
      - primary

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.0

      - run: npm install
      - run: npm run ci
